spring:
  profiles:
    active: local

  application:
    name: backend

  session:
    store-type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

        dialect: org.hibernate.dialect.MariaDBDialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

